API_ID: 26032794
API_HASH: "1ccced9f1c971ee459e5c539792cb2f6"
BOT_TOKEN: "6973378210:AAG9WARDLIVfvmRZ8QQ6tsJdyUCvcGtyO1s"


MONGO_URL: 
REDIS_URI: "redis-14759.c274.us-east-1-3.ec2.cloud.redislabs.com"
REDIS_PORT: 14759
REDIS_PASS: "Nzv4WRFrKa2JOcyr55VIJ1Suvq71EZbb"

SESSION_API_ID: 
SESSION_API_HASH: 
SESSION_STRING: 

ADMINS: 6321377431

OWNER: 6321377431

BOT_PIC: 'https://te.legra.ph/file/06f1ad2e0ce823a476994.jpg'
OWNER_PIC: 'https://te.legra.ph/file/06f1ad2e0ce823a476994.jpg'

SUPPORT_CHAT: roldexversechats 
# LOG_CHAT: 
LOG_CHAT: 



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

